# Deep Dive into Matplotlib and Seaborn

## Importing Libraries

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Loading Data

### Loading Austin Data

In [2]:
austin = pd.read_csv(r"C:\Users\user\Desktop\Python-Deep-Dive-Demos\Data\austin_weather.csv")

In [3]:
austin.head()

,STATION,NAME,DATE,MLY-CLDD-BASE45,MLY-CLDD-BASE50,MLY-CLDD-BASE55,MLY-CLDD-BASE57,MLY-CLDD-BASE60,MLY-CLDD-BASE70,MLY-CLDD-BASE72,...,MLY-TMIN-AVGNDS-LSTH060,MLY-TMIN-AVGNDS-LSTH070,MLY-TMIN-NORMAL,MLY-TMIN-PRBOCC-LSTH016,MLY-TMIN-PRBOCC-LSTH020,MLY-TMIN-PRBOCC-LSTH024,MLY-TMIN-PRBOCC-LSTH028,MLY-TMIN-PRBOCC-LSTH032,MLY-TMIN-PRBOCC-LSTH036,MLY-TMIN-STDDEV
0,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",1,190,103,50,35,18,1,-7777,...,302,310,36.3,298,570,839,967,997,1000,2.9
1,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",2,228,132,68,49,29,3,1,...,264,280,39.4,103,327,614,867,973,999,3.2
2,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",3,446,306,185,146,98,13,6,...,270,308,46.6,10,73,242,494,761,928,3.6
3,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",4,668,519,373,318,240,53,32,...,193,287,54.7,0,0,0,48,189,453,4.1
4,USW00013904,"AUSTIN BERGSTROM INTERNATIONAL AIRPORT, TX US",5,936,781,626,564,471,181,134,...,89,250,63.7,0,0,0,0,0,0,2.5

### Loading Seattle Data

In [4]:
seattle = pd.read_csv(r"C:\Users\user\Desktop\Python-Deep-Dive-Demos\Data\seattle_weather.csv")

In [5]:
seattle.head()

,STATION,NAME,DATE,MLY-CLDD-BASE45,MLY-CLDD-BASE50,MLY-CLDD-BASE55,MLY-CLDD-BASE57,MLY-CLDD-BASE60,MLY-CLDD-BASE70,MLY-CLDD-BASE72,...,MLY-TMIN-AVGNDS-LSTH060,MLY-TMIN-AVGNDS-LSTH070,MLY-TMIN-NORMAL,MLY-TMIN-PRBOCC-LSTH016,MLY-TMIN-PRBOCC-LSTH020,MLY-TMIN-PRBOCC-LSTH024,MLY-TMIN-PRBOCC-LSTH028,MLY-TMIN-PRBOCC-LSTH032,MLY-TMIN-PRBOCC-LSTH036,MLY-TMIN-STDDEV
0,USC00456295,"PALMER 3 ESE, WA US",1,13.0,1.0,-7777.0,0.0,0.0,0.0,0.0,...,310.0,310.0,34.0,168.0,327.0,615.0,877.0,987.0,1000.0,2.8
1,USC00456295,"PALMER 3 ESE, WA US",2,23.0,3.0,-7777.0,-7777.0,0.0,0.0,0.0,...,280.0,280.0,33.9,132.0,275.0,515.0,800.0,963.0,1000.0,3.1
2,USC00456295,"PALMER 3 ESE, WA US",3,50.0,11.0,1.0,-7777.0,-7777.0,0.0,0.0,...,310.0,310.0,35.9,5.0,47.0,111.0,393.0,848.0,1000.0,2.1
3,USC00456295,"PALMER 3 ESE, WA US",4,108.0,40.0,12.0,7.0,3.0,-7777.0,0.0,...,300.0,300.0,38.3,0.0,0.0,5.0,123.0,571.0,978.0,2.0
4,USC00456295,"PALMER 3 ESE, WA US",5,255.0,130.0,56.0,38.0,19.0,1.0,-7777.0,...,310.0,310.0,43.5,0.0,0.0,0.0,0.0,83.0,610.0,2.0

## Data Cleaning and EDA

### Cleaning and EDA for Seattle

In [6]:
# Checking for missing values in the seattle_csv dataset
seattle.isna().sum()

STATION                     0
NAME                        0
DATE                        0
MLY-CLDD-BASE45            24
MLY-CLDD-BASE50            24
                           ..
MLY-TMIN-PRBOCC-LSTH024    24
MLY-TMIN-PRBOCC-LSTH028    24
MLY-TMIN-PRBOCC-LSTH032    24
MLY-TMIN-PRBOCC-LSTH036    24
MLY-TMIN-STDDEV            24
Length: 80, dtype: int64

In [7]:
# Checking for Duplicates in the seattle_csv dataset
seattle.duplicated().sum()

np.int64(0)

In [8]:
seattle.info()

<class 'pandas.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 80 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   STATION                  204 non-null    str
 1   NAME                     204 non-null    str
 2   DATE                     204 non-null    int64
 3   MLY-CLDD-BASE45          180 non-null    float64
 4   MLY-CLDD-BASE50          180 non-null    float64
 5   MLY-CLDD-BASE55          180 non-null    float64
 6   MLY-CLDD-BASE57          180 non-null    float64
 7   MLY-CLDD-BASE60          180 non-null    float64
 8   MLY-CLDD-BASE70          180 non-null    float64
 9   MLY-CLDD-BASE72          180 non-null    float64
 10  MLY-CLDD-NORMAL          180 non-null    float64
 11  MLY-DUTR-NORMAL          180 non-null    float64
 12  MLY-DUTR-STDDEV          180 non-null    float64
 13  MLY-GRDD-BASE40          180 non-null    float64
 14  MLY-GRDD-BASE45          180 non-null    float64
 15  MLY-GRDD-BASE50          180 non-null    float64
 16  MLY-GRDD-BASE55          180 non-null    float64
 17  MLY-GRDD-BASE57          180 non-null    float64
 18  MLY-GRDD-BASE60          180 non-null    float64
 19  MLY-GRDD-BASE65          180 non-null    float64
 20  MLY-GRDD-BASE70          180 non-null    float64
 21  MLY-GRDD-BASE72          180 non-null    float64
 22  MLY-GRDD-TB4886          180 non-null    float64
 23  MLY-GRDD-TB5086          180 non-null    float64
 24  MLY-HTDD-BASE40          180 non-null    float64
 25  MLY-HTDD-BASE45          180 non-null    float64
 26  MLY-HTDD-BASE50          180 non-null    float64
 27  MLY-HTDD-BASE55          180 non-null    float64
 28  MLY-HTDD-BASE57          180 non-null    float64
 29  MLY-HTDD-BASE60          180 non-null    float64
 30  MLY-HTDD-NORMAL          180 non-null    float64
 31  MLY-PRCP-25PCTL          156 non-null    float64
 32  MLY-PRCP-50PCTL          156 non-null    float64
 33  MLY-PRCP-75PCTL          156 non-null    float64
 34  MLY-PRCP-AVGNDS-GE001HI  156 non-null    float64
 35  MLY-PRCP-AVGNDS-GE010HI  156 non-null    float64
 36  MLY-PRCP-AVGNDS-GE050HI  156 non-null    float64
 37  MLY-PRCP-AVGNDS-GE100HI  156 non-null    float64
 38  MLY-PRCP-NORMAL          204 non-null    float64
 39  MLY-SNOW-25PCTL          120 non-null    float64
 40  MLY-SNOW-50PCTL          120 non-null    float64
 41  MLY-SNOW-75PCTL          120 non-null    float64
 42  MLY-SNOW-AVGNDS-GE001TI  120 non-null    float64
 43  MLY-SNOW-AVGNDS-GE010TI  120 non-null    float64
 44  MLY-SNOW-AVGNDS-GE030TI  120 non-null    float64
 45  MLY-SNOW-AVGNDS-GE050TI  120 non-null    float64
 46  MLY-SNOW-AVGNDS-GE100TI  120 non-null    float64
 47  MLY-SNOW-NORMAL          120 non-null    float64
 48  MLY-SNWD-AVGNDS-GE001WI  120 non-null    float64
 49  MLY-SNWD-AVGNDS-GE003WI  120 non-null    float64
 50  MLY-SNWD-AVGNDS-GE005WI  120 non-null    float64
 51  MLY-SNWD-AVGNDS-GE010WI  120 non-null    float64
 52  MLY-TAVG-NORMAL          180 non-null    float64
 53  MLY-TAVG-STDDEV          180 non-null    float64
 54  MLY-TMAX-AVGNDS-GRTH040  180 non-null    float64
 55  MLY-TMAX-AVGNDS-GRTH050  180 non-null    float64
 56  MLY-TMAX-AVGNDS-GRTH060  180 non-null    float64
 57  MLY-TMAX-AVGNDS-GRTH070  180 non-null    float64
 58  MLY-TMAX-AVGNDS-GRTH080  180 non-null    float64
 59  MLY-TMAX-AVGNDS-GRTH090  180 non-null    float64
 60  MLY-TMAX-AVGNDS-GRTH100  180 non-null    float64
 61  MLY-TMAX-AVGNDS-LSTH032  180 non-null    float64
 62  MLY-TMAX-NORMAL          180 non-null    float64
 63  MLY-TMAX-STDDEV          180 non-null    float64
 64  MLY-TMIN-AVGNDS-LSTH000  180 non-null    float64
 65  MLY-TMIN-AVGNDS-LSTH010  180 non-null    float64
 66  MLY-TMIN-AVGNDS-LSTH020  180 non-null    float64
 67  MLY-TMIN-AVGNDS-LSTH032  180 non-null    float64
 68  MLY-TMIN-AVGNDS-LSTH040  180 non-null    float64
 69  MLY-TMIN-AVGNDS-LSTH050  180 non-null    float64
 70  MLY-TMIN-AVGNDS-LSTH060  180 non-null    float64
 71  MLY-TMIN-AVGNDS-LSTH070  180 non-null    float64
 72  MLY-TMIN-NORMAL          180 non-null    float64
 73  MLY-TMIN-PRBOCC-LSTH016  180 non-null    float64
 74  MLY-TMIN-PRBOCC-LSTH020  180 non-null    float64
 75  MLY-TMIN-PRBOCC-LSTH024  180 non-null    float64
 76  MLY-TMIN-PRBOCC-LSTH028  180 non-null    float64
 77  MLY-TMIN-PRBOCC-LSTH032  180 non-null    float64
 78  MLY-TMIN-PRBOCC-LSTH036  180 non-null    float64
 79  MLY-TMIN-STDDEV          180 non-null    float64
dtypes: float64(77), int64(1), str(2)
memory usage: 127.6 KB

In [ ]:
# Craete a new column on both dataframes called "month" that contains the month of the date column 
# eg 1 = Jan 2 = Feb .. , 11 = Nov , 12 = Dec